name: "Build & Deploy"
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Build
              run: |
                  echo "${{secrets.ENVIRONMENT}}" > .env
                  cat .env
                  npm ci
                  npm run build
            - name: Upload dist/
              uses: actions/upload-artifact@v1
              with:
                  name: dist
                  path: dist
    deploy:
        needs: build
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Download dist/
              uses: actions/download-artifact@v1
              with:
                  name: dist
                  path: dist
            - run: npm install -g firebase-tools
            - run: firebase -V
            - run: firebase deploy --project together-india --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
